### ISSUE TITLE
Problem with getProperty

### ISSUE THREAD

**Issue by kamilmowinski** [seballot/ep_tables2#20]
Hi everyone,
i have a problem with my instance of etherpad. I installed the following plugins: 
align, author_neat, colors, comments_page, copy_paste_images, countable, cursortrace, font_family, font_size, headings2, line_height, page_view, previewimages, spellcheck, table_of_contents.

And now i am trying to install you tables2 plugin. When i do it i got typeerror in console:

Uncaught TypeError: Cannot read property 'getProperty' of undefined

from menu-min.js file. 

I havent idea what i am doing wrong,
could you help me?

Thank You

**Comment by DirtyHao** [comment]
i have the same problem。 Did you fixed it?

**Comment by kamilmowinski** [comment]
Could you give me a link to topic? I rly dont remember this problem. 

Kamil Mówiński

Dnia 13.04.2016 o godz. 05:16 DirtyHao <notifications@github.com> napisał(a):

**Comment by seballot** [comment]
Hi, I cannot reproduce anymore, so closing for now
